config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  path: "konto",
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'cmon_let_me_in' }

  root to: 'pages#home'
  get 'cookies', to: 'pages#cookies'

  resources :categories, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :products
  end

  resources :hours, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  mount_uploader :icon, PhotoUploader

  has_many :products, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/models/hour.rb
class Hour < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  # mount_uploader :photo, PhotoUploader
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  include Pundit
  #
  # # Pundit: white-list approach.
  after_action :verify_authorized, only: [:new, :create, :edit, :update, :destroy], unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: [:new, :create, :edit, :update, :destroy], unless: :skip_pundit?
  #
  # # Uncomment when you *really understand* Pundit!
  # # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # # def user_not_authorized
  # #   flash[:alert] = "You are not authorized to perform this action."
  # #   redirect_to(root_path)
  # # end
  #
  private
  #
  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  def index
    @categories = Category.all
  end

  def show
  end

  def edit
    authorize @category
  end

  def update
    authorize @category
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end


  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :set_hour, only: [:edit, :update]
  def edit
    authorize @hour
  end

  def update
    authorize @hour
    if @hour.update(hour_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_hour
    @hour = Hour.find(params[:id])
  end

  def hour_params
    params.require(:hour).permit(:hours)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @categories = Category.all
    @hours = Hour.all.order(:id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    # @user = current_user
    @product = Product.new(product_params)
    authorize @product
    @product.category = @category
    if @product.save!
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
    authorize @product
  end

  def update
    authorize @product
    if @product.update(product_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to category_path(@category)
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description)
  end


  def set_category
    @category = Category.find(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<div class="row row-no-padding" style="margin-top: 120px;" >
  <%= render 'shared/back_button', link: category_path(@category) %>
  <div class="col-xs-12 col-sm-6">
    <h3>Edytuj kategorię</h3>
    <%= simple_form_for @category, url: {action: "update"} do |f| %>
    <%= f.input :name %>
    <%= f.input :description, label: "Opis kategorii", input_html: { rows: 10 } %>
    <div class="button-center">
      <%= f.submit "Aktualizuj", class: "btn btn-success" %>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="category-banner" style="background-image: linear-gradient(-225deg, rgba(135, 135, 135, 0.8) 0%, rgba(135,135,135,0.4) 50%), url(<%= @category.photo %>);">
  <div class="banner-content">
    <div class="cat-banner-title">
      <h1><%= @category.name %></h1>
    </div>
  </div>
</div>
<div class="cat-content">
  <div class="row row-no-padding">
    <%= render 'shared/back_button', link: root_path %>
    <% if user_signed_in? && current_user.admin? %>
    <%= render 'shared/edit_button', link: edit_category_path(@category) %>
    <%= render 'shared/new_product_button', link: new_category_product_path(@category) %>
    <% end %>
  </div>
  <div class="row row-no-padding">

  </div>
</div>


<!-- tabs -->

<div class="row row-no-padding">
  <div class="col-xs-12 col-sm-4">
    <ul class="products-tabs" id="jumping" role="tablist">
      <li role="presentation" class="product-tab active"><a href="#category" data-toggle="tab">
        <h5>Opis usług</h5>
      </a></li>
      <% @category.products.each do |product| %>
      <li role="presentation" class="product-tab"><a href="#<%= product.id %>" data-toggle="tab">
        <h5><%= product.name %></h5>
      </a></li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-8">
    <div class="tab-content product-tab-content">
      <div class="tab-pane active" id="category" role="tabpanel">
        <div class="cat-description">
          <p><%= simple_format(@category.description) %></p>
        </div>
      </div>
      <% @category.products.each do |product| %>
      <div class="tab-pane" id="<%= product.id %>" role="tabpanel">
        <div class="cat-description">
          <p><%= simple_format(product.description) %></p>
          <br><br>
          <% if user_signed_in? && current_user.admin? %>
          <%= link_to "EDYTUJ", edit_category_product_path(@category, product), class:"btn-product-details" %>
          <%= link_to "USUŃ", category_product_path(@category, product), method: :delete, data: {confirm: "Na pewno?"}, class:"btn-product-details" %>

          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/hours/edit.html.erb
<div class="row row-no-padding" style="margin-top: 120px;" >
  <%= render 'shared/back_button', link: root_path %>
  <div class="col-xs-12 col-sm-6">
    <h3>Edytuj godziny otwarcia</h3>
    <%= simple_form_for @hour, url: {action: "update"} do |f| %>
    <p><%= @hour.day %> (format: hh.mm - hh.mm lub "Nieczynne")</p>
    <br>
    <%= f.input :hours, label: "ustaw" %>
    <div class="button-center">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Alcar Lublin - zapiezpieczenia samochodowe, alarmy, klimatyzacja, GPS, wymiana opon, elektromechanika, akcesoria.">
    <title>ALCAR Lublin - Lech Żuber</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>

  </head>
  <body>
    <%= render 'shared/navbar_all' %>

    <%= yield %>
    <script>
      window.addEventListener("load", function(){
      window.cookieconsent.initialise({
        "palette": {
          "popup": {
            "background": "#aa0000",
            "text": "#ffdddd"
          },
          "button": {
            "background": "#ff0000"
          }
        },
        "showLink": false,
        "theme": "classic",
        "position": "bottom-right",
        "content": {
          "message": "W ramach naszej strony stosujemy pliki cookies w celu świadczenia usług na najwyższym poziomie, dzięki czemu dostosowuje się ona do Państwa indywidualnych potrzeb. Korzystanie z witryny bez zmiany ustawień cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. ",
          "dismiss": "Rozumiem!"
        }
      })});
    </script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/cookies.html.erb
<h1>COOKIES</h1>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(135, 135, 135, 0.8) 0%, rgba(135,135,135,0.4) 50%), url(<%= image_path 'banner.jpg' %>);">
    <div class="banner-content">
      <h1 class="banner-title">SERWIS SAMOCHODOWY</h1>
        <%= link_to '#oferta', class: "btn btn-offer link-no-deco" do %>
        <p class='oferta'>Sprawdź naszą ofertę</p>
        <% end %>
    </div>
    <div class='eu-content'>
      <p class='eu-note'>Przedmiot projektu: wsparcie utrzymania działalności gospodarczej przedsiębiorstwa,
        które znalazło się w trudnej sytuacji nagłego niedoboru w związku z wystąpieniem
        pandemii COVID-19.
      </p>
      <div>
        <%= image_tag('eu.png', height:60)%>
        <%= image_tag('fe.png', height:60)%>
        <%= image_tag('pl.png', height:60)%>
        <%= image_tag('lb.png', height:40)%>
      </div>
    </div>
</div>

<div id="oferta" class="content-box">
  <div class="row row-no-padding">
    <br>
    <% @categories.each do |category| %>
    <%= link_to category_path(category) do %>
    <div class="col-xs-12 col-md-4 text-center cat-details">
      <%= image_tag(category.icon.url, class: "cat-icon") %>
      <h3><%= category.name %></h3>
    </div>
    <% end %>
    <% end %>
  </div>
  <div class="spacer"></div>
</div>

<!-- tabs -->

<!-- <div class="row row-no-padding text-center company" id="zaklad"><h2>O FIRMIE</h2></div> -->
<div id="zaklad" class="row row-no-padding text-center about">
  <div class="col-xs-12 col-sm-5 info-highlight">
    <h1>DZIAŁAMY </h1>
    <h1>OD <span style="color: #FF0025; font-size: 92px;">1986</span></h1>
  </div>
  <div class="col-xs-12 col-sm-6 company-description">
    <h4>ALCAR już od <strong>ponad 30 lat</strong> działa na rynku zabezpieczeń pojazdów.</h4>
    <br>
    <p>W wyniku rozwoju rynku i potrzeb klientów działalność była konsekwentnie
      rozszerzana o usługi z zakresu <strong>elektromechaniki</strong>, <strong>obsługi serwisowej</strong> pojazdu
      (oleje, filtry , klocki hamulcowe itp ), <strong>klimatyzacji</strong>, <strong>wymiany opon</strong> i obsługi
      <strong>systemów GPS</strong>.
      <br><br>
      O jakości usług świadczyć może ilość zadowolonych klientów,
      którzy zwracają się do nas z problemami o różnym podłożu. Współpracujemy
      zarówno z klientami indywidualnymi, jak i przedsiębiorstwami.</p>
    </div>

  </div>
  <ul class="company-tabs" id="jumping" role="tablist">
    <li role="presentation" class="company-tab active"><a href="#raz" data-toggle="tab">
      <h3 class="hidden-xs">Zakład najwyższego zaufania</h3>
      <h6 class="hidden-sm hidden-md hidden-lg">Zaufanie</h6>
    </a></li>
    <li role="presentation" class="company-tab"><a  href="#dwa" data-toggle="tab">
      <h3 class="hidden-xs">Profesjonalizm</h3>
      <h6 class="hidden-sm hidden-md hidden-lg">Profesjonalizm</h6>
    </a></li>
    <li role="presentation" class="company-tab"><a  href="#trzy" data-toggle="tab">
      <h3 class="hidden-xs">USŁUGI</h3>
      <h6 class="hidden-sm hidden-md hidden-lg">USŁUGI</h6>
    </a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane tab-pane-padding active" id="raz" role="tabpanel">
      <div class="row row-no-padding">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left company-details">
          <h3>Tytuł Zakładu Najwyższego Zaufania</h3>
          <p>nadany przez TECHOM Nr 70/97.
            <br><br>
          <h3>Autoryzacja</h3>
            przez Przemysłowy Instytut Motoryzacji (Nr 15/BLE/18/ZK/98).
            <br><br>

            Jako Zakład Kontroli Zabezpieczeń Przeciwkradzieżowych wykonujemy dla potrzeb
            firm ubezpieczeniowych oraz osób fizycznych oceny skuteczności zabezpieczeń z
            określeniem ich klasy. </p>
          </div>
        </div>
      </div>
      <div class="tab-pane tab-pane-padding" id="dwa" role="tabpanel">
        <div class="row row-no-padding">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left company-details">
            <p>
              Posiadane uprawnienia i wiadomości pozwalają firmie na prowadzenie
              profesjonalnych usług w zakresie doboru i montażu zabezpieczeń dla pojazdów
              specjalistycznych min. tj. bankowozów..
            </p>
            <p>
              W celu świadczenia usług używamy sprzętu
              najwyższej klasy gwarantującego wysoką i trwałą jakość.
            </p>
            <p>
              Kadra pracownicza
              posiada licencje pracowników zabezpieczenia technicznego wydane przez Komendę
              Wojewódzką Policji.
            </p>
          </div>
        </div>
      </div>
      <div class="tab-pane tab-pane-padding" id="trzy" role="tabpanel">
        <div class="row row-no-padding">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left company-details">
            <p>Zakład oferuje szeroki zakres usług obejmujący zabezpieczenia, montaż,
              naprawę i konserwację klimatyzacji, wymianę opon, montaż GPS,  naprawy z
              zakresu elektromechaniki pojazdowej.
            </p>
            <p>Prowadzimy zaopatrzenie serwisów
              samochodowych oraz instalatorów indywidualnych w sprzęt i akcesoria
              zabezpieczające.</p>
              <p>Oferujemy sprzęt radiowy CB z montażem. Wykonujemy
                diagnostykę komputerową układów elektrycznych pojazdów, sterowników silnika,
                układów ABS, układów poduszek powietrznych itp.</p>
                <br>
                <p>Więcej informacji znaleźć można w ofercie.</p>
              </div>
            </div>
          </div>
        </div>

        <div id="kontakt" class="contact-box">
          <div class="row row-no-padding text-center contact"><h2>KONTAKT</h2></div>


          <div class="row row-no-padding">
            <div class="col-xs-12 col-md-6 address-box">
              <div class="address">
                <h2>ALCAR Lech Żuber</h2>
                <br>
                <div class="address-details">
                  <i class="fas fa-map-marker-alt"></i> <p> ul. Kraszewskiego 31, 20-463 Lublin <br> NIP: 7120306343</p>
                </div>
                <br>
                <div class="address-details">
                  <i class="fas fa-phone"></i><p>81 744 18 52</p>
                </div>
                <br>
                <div class="address-details">
                  <i class="fa fa-at"></i><p>alcar@alcar.lublin.pl</p>
                </div>
                <div class="opening-hours">
                  <h3 class="opening-hours-title">Godziny otwarcia</h3>
                  <div style="background-color: #f4f4f4;">
                    <% @hours.each do |hour| %>
                    <div class="day">
                      <h5><strong><%= hour.day %></strong>
                        <% if user_signed_in? && current_user.admin? %>
                        <%= link_to "| EDYTUJ |", edit_hour_path(hour), style:"color: #2b2b2b;" %>
                        <% end %>
                      </h5>
                      <p><%= hour.hours %></p>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-md-6">
              <div
              id="map"
              style="width: 100%;
              height: 600px; display: flex;"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
              ></div>
            </div>
          </div>

        </div>

app/views/products/_form.html.erb
<div class="row row-no-padding">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <%= simple_form_for [category, product] do |f| %>
    <%= f.input :name, label: "Nazwa" %>
    <%= f.input :description, label: "Opis", input_html: { rows: 10 } %>
        <div class="button-center">
        <%= f.submit "Zapisz", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="row row-no-padding" style="margin-top: 120px;" >
  <%= render 'shared/back_button', link: category_path(@category) %>
  <div class="col-xs-12 col-sm-5">
    <h3>Edytuj usługę</h3>
    <br>
  </div>
</div>
<%= render 'form', product: @product, category: @category %>

app/views/products/index.html.erb
<% @category.products.each do |product| %>
  <h2><%= product.name %></h2>
  <br>
<% end %>

app/views/products/new.html.erb
<div class="row row-no-padding" style="margin-top: 120px;" >
  <%= render 'shared/back_button', link: category_path(@category) %>
  <div class="col-xs-12 col-sm-5">
    <h3>Dodaj usługę</h3>
    <br>
  </div>
</div>
<%= render 'form', product: @product, category: @category %>

app/views/products/show.html.erb
<div class="category-banner" style="background-image: linear-gradient(-225deg, rgba(135, 135, 135, 0.8) 0%, rgba(135,135,135,0.4) 50%), url(<%= @product.category.photo %>);">
  <div class="banner-content">
    <div class="cat-banner-title">
      <h1><%= @product.name %></h1>
    </div>
  </div>
</div>

<div class="cat-content">
  <div class="row row-no-padding">
    <%= render 'shared/back_button', link: category_path(@product.category) %>
    <%= render 'shared/edit_button', link: edit_category_product_path(@product) %>

  </div>
  <div class="row row-no-padding">
    <div class="col-xs-12 col-sm-4 cat-description"><p><%= @product.long_description %></p></div>
    <div class="col-xs-12 col-sm-7 cat-description">
      <h3 class="text-center">Usługi</h3>
      <% @product.options.each do |option| %>
        <div class="product-option">
          <div class="cat-product-details">
            <h5><%= option.name %></h5>
          </div>
          <p class="cat-product-price">ceny od xxx pln</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_back_button.html.erb
  <div class="col-xs-2 col-sm-3">
    <%= link_to link, class: "link-back btn-back btn-navigate" do %>
      <%= image_tag('back.svg', width: '24px') %> <h5 class="hidden-xs" style="margin-left: 10px;">POWRÓT</h5>
    <% end %>
  </div>

app/views/shared/_cookies.html.erb
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  },
  "content": {
    "message": "W ramach naszej strony stosujemy pliki cookies w celu świadczenia usług na najwyższym poziomie, dzięki czemu dostosowuje się ona do Państwa indywidualnych potrzeb. Korzystanie z witryny bez zmiany ustawień cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. ",
    "dismiss": "Rozumiem!",
    "link": "<%= link_to "Szczegóły", cookies_path %>"
  }
})});
</script>

app/views/shared/_edit_button.html.erb
  <div class="col-xs-2 col-sm-3">
    <%= link_to link, class: "link-back btn-back btn-navigate" do %>
      <%= image_tag('gear.svg', width: '24px') %> <h5 class="hidden-xs" style="margin-left: 10px;">EDYTUJ</h5>
    <% end %>
  </div>

app/views/shared/_footer.html.erb
<div class="footer hidden-xs">
  <div class="footer-links">
    <p>ALCAR Lech Żuber</p>
    <p>|</p>
    <p>ul. Kraszewskiego 31, Lublin</p>
    <p>|</p>
    <p>tel. 81 744 18 52</p>
  </div>
  <div class="footer-copyright">
    <p>made by <a href="http://zuzazuber.com" class="link-no-deco">Zuza</a></p>
  </div>
</div>

app/views/shared/_navbar_all.html.erb
<div class="navbar-alcar navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path do %>
  <%= image_tag('Alcar-logo.png', class: "navbar-brand") %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-alcar-right hidden-xs hidden-sm">
      <!-- Links when logged in -->
      <a href="<%= root_path %>#oferta" class="navbar-alcar-item navbar-alcar-link">OFERTA</a>
      <a href="<%= root_path %>#zaklad" class="navbar-alcar-item navbar-alcar-link">ZAKŁAD</a>
      <a href="<%= root_path %>#kontakt" class="navbar-alcar-item navbar-alcar-link">KONTAKT</a>
      <!-- Avatar with dropdown menu -->
    <% if user_signed_in? && current_user.admin? %>
    <div class="dropdown">
      <div class="navbar-alcar-item navbar-alcar-link btn-product-details" data-toggle="dropdown" role="button">ADMIN</div>
      <% elsif user_signed_in? %>
      <div class="navbar-alcar-item navbar-alcar-link btn-product-details" data-toggle="dropdown" role="button">USER</div>
      <% end %>
      <ul class="dropdown-menu dropdown-menu-right navbar-alcar-dropdown-menu">
        <li><%= link_to "WYLOGUJ", destroy_user_session_path, method: :delete, class:"navbar-alcar-item navbar-alcar-link" %></li>
      </ul>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-alcar-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-alcar-dropdown-menu">
        <li><a href="<%= root_path %>#oferta" class="navbar-alcar-item navbar-alcar-link">OFERTA</a></li>
        <li><a href="<%= root_path %>#zaklad" class="navbar-alcar-item navbar-alcar-link">ZAKŁAD</a></li>
        <li><a href="<%= root_path %>#kontakt" class="navbar-alcar-item navbar-alcar-link">KONTAKT</a></li>
        <% if user_signed_in? && current_user.admin? %>
        <li><%= link_to "WYLOGUJ", destroy_user_session_path, method: :delete, class:"navbar-alcar-item navbar-alcar-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>


</div>

app/views/shared/_new_product_button.html.erb
<div class="col-xs-2 col-sm-3">
  <%= link_to link, class: "link-back btn-back  btn-navigate btn-new" do %>
    <%= image_tag('tool.svg', width: '24px') %> <h5 class="hidden-xs" style="margin-left: 10px;">NOWA USŁUGA</h5>
  <% end %>
</div>